### ISSUE TITLE
include "verified" property data-models/ngsi-context.jsonld

### ISSUE THREAD

**Issue by nikosft** [FIWARE/tutorials.NGSI-LD#17]
Tutorial examples use the `verified` property of property (e.g., the request in this [example](https://ngsi-ld-tutorials.readthedocs.io/en/latest/working-with-%40context.html#2-request)) However, this term is not included in the [context file](https://github.com/FIWARE/tutorials.Getting-Started/blob/NGSI-LD/data-models/ngsi-context.jsonld)

As a matter of fact, if you replace the context url in that request with 
```
https://raw.githubusercontent.com/FIWARE/tutorials.Getting-Started/NGSI-LD/data-models/ngsi-context.jsonld
```
and then put the output in json-ld playground, you will observe that "verified" property is ignored. 

[Proof of concept](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22id%22%3A%22urn%3Angsi-ld%3ABuilding%3Afarm001%22%2C%22type%22%3A%22Building%22%2C%22category%22%3A%7B%22type%22%3A%22Property%22%2C%22value%22%3A%5B%22farm%22%5D%7D%2C%22address%22%3A%7B%22type%22%3A%22Property%22%2C%22value%22%3A%7B%22streetAddress%22%3A%22Gro%C3%9Fer%20Stern%201%22%2C%22addressRegion%22%3A%22Berlin%22%2C%22addressLocality%22%3A%22Tiergarten%22%2C%22postalCode%22%3A%2210557%22%7D%2C%22verified%22%3A%7B%22type%22%3A%22Property%22%2C%22value%22%3Atrue%7D%7D%2C%22location%22%3A%7B%22type%22%3A%22GeoProperty%22%2C%22value%22%3A%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B13.3505%2C52.5144%5D%7D%7D%2C%22name%22%3A%7B%22type%22%3A%22Property%22%2C%22value%22%3A%22Victory%20Farm%22%7D%2C%22%40context%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2FFIWARE%2Ftutorials.Getting-Started%2FNGSI-LD%2Fdata-models%2Fngsi-context.jsonld%22%7D&context=%7B%7D)

**Comment by jason-fox** [comment]
I have updated the `@context` file as you suggested. However, the reasoning behind your comment is only correct for JSON-LD, (and the JSON-LD playground) and not NGSI-LD systems themselves.

The NGSI-LD specification states that the core `@context` should be attached to any NGSI-LD call to a context broker - therefore the *implied context* is:

```json
  "@context" : [ 
      "https://raw.githubusercontent.com/FIWARE/tutorials.Getting-Started/NGSI-LD/data-models/ngsi-context.jsonld",
      "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld "]
```

The final element of the core `@context` states:

```json
"@vocab": "https://uri.etsi.org/ngsi-ld/default-context/"
```

Which means that for NGSI-LD systems the unmapped `verified` attribute would expand to `https://uri.etsi.org/ngsi-ld/default-context/verified` *within an LD context broker*.

However for me personally, the fact that context brokers always append core `@context` isn't clear to non NGSI-LD systems, therefore, for the avoidance of doubt, personally, I would always create two distinct `@context` files and link to an explicit 2 context file mapping `@context file like this:



```json
{
  "@context": [
        "https://raw.githubusercontent.com/FIWARE/tutorials.Getting-Started/NGSI-LD/data-models/ngsi-context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ]
}
```

rather than Link to  `https://raw.githubusercontent.com/FIWARE/tutorials.Getting-Started/NGSI-LD/data-models/ngsi-context.jsonld` directly.

**Comment by nikosft** [comment]
BTW the context file defines
```
"fiware": "https://uri.fiware.org/ns/data-models#"
```
But https://uri.fiware.org/ns/data-models is not resolvable, on the other hand https://uri.fiware.org/ns/dataModels is and includes the documentation of the defined attributes. So maybe it is better to use that, i.e., 

```
"fiware": "https://uri.fiware.org/ns/dataModels#"
```

**Comment by jason-fox** [comment]
That makes sense too, so I have updated that as well.
