### ISSUE TITLE
integration issue 

### ISSUE THREAD

**Issue by Neeraj-Nec** [FIWARE/tutorials.NGSI-LD#6]
Hi ,

I am integrating IOT agent from FogFlow using orion broker . In this scenario IOT agent send the data to the Orion broker  and FogFlow have subscribe to the Orion broker to get the data . FogFlow is getting the following data in the notification .

```json
{
	"@context": "https://fiware.github.io/data-models/context.jsonld",
	"id": "urn:ngsi-ld:Device:water001",
	"type": "Device",
	"heartRate": {
		"type": "Property",
		"value": {
			"@type": "Intangible",
			"@value": null
		},
		"unitCode": "5K"
	},
	"status": {
		"type": "Property",
		"value": {
			"@type": "Intangible",
			"@value": null
		}
	},
	"location": {
		"type": "GeoProperty",
		"value": {
			"type": "Point",
			"coordinates": [0, 0]
		}
	},
	"controlledAsset": {
		"type": "Relationship",
		"object": "urn:ngsi-ld:Building:barn001"
	},
	"category": {
		"type": "Property",
		"value": "sensor"
	},
	"supportedProtocol": {
		"type": "Property",
		"value": "ul20"
	},
	"on_status": {
		"type": "Property",
		"value": {
			"@type": "commandStatus",
			"@value": "UNKNOWN"
		}
	},
	"on_info": {
		"type": "Property",
		"value": {
			"@type": "commandResult",
			"@value": " "
		}
	},
	"off_status": {
		"type": "Property",
		"value": {
			"@type": "commandStatus",
			"@value": "UNKNOWN"
		}
	},
	"off_info": {
		"type": "Property",
		"value": {
			"@type": "commandResult",
			"@value": " "
		}
	},
	"on": {
		"type": "command",
		"value": ""
	},
	"off": {
		"type": "command",
		"value": ""
	}
}
```

This data has @type and @value at some places. I am confused whether this data is correct or not , because if we use same data to create entity i am getting error of "NOT A VALID JSON" Scorpio broker .

**Comment by jason-fox** [comment]
If you paste the body into the [JSON-LD Playground](https://json-ld.org/playground/) (and move the `@context` line to **Use remote document**) then you will see that the payload is valid JSON-LD.

The issue comes down to what needs to be done with `null` values -  according to the current [ETSI specification](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf):

> **5.2.1 Introduction**
>
>  None of the members described admit a null value, except when they are used in the context of an update
> operation (see clause 5.5.8) and implementations shall raise an error of type **BadRequestData** if a `null` 
> value is encountered.

Therefore you can't currently define an unknown value as:

```json
"status": {
     "type": "Property",
     "value": null
}
```

The only option is to define an object that resolves to `null`. This is how the the [IoT Agent node library](https://iotagent-node-lib.readthedocs.io/) currently does it. My guess is this is  probably an issue with the JSON parser within the Scorpio broker. If this incompatibility isn't working for you, then either it needs to be fixed in Scorpio or amended in the IoT Agent node library-  the definition is on this line [here](https://github.com/telefonicaid/iotagent-node-lib/blob/master/lib/services/ngsi/entities-NGSI-LD.js#L46) - maybe you could try it with a `null`.

**Comment by Neeraj-Nec** [comment]
The notification data is coming from Orion broker when I was update the data on IOT agent . if the null is the issue then still the issue is from Orion broker

**Comment by jason-fox** [comment]
Then please raise this against Orion-LD

**Comment by jason-fox** [comment]
Closing since this is not an issue with the tutorials themselves.
