### ISSUE TITLE
relationships of properties are ambiguous

### ISSUE THREAD

**Issue by minhtaile2712** [FIWARE/tutorials.NGSI-LD#9]
In section "Entity Relationships", at subsection "RELATIONSHIPS OF PROPERTIES", the document showed how to retrieve the temperature of a barn (the data has been duplicated from the **TemperatureSensor** to the **Building**), but didn't provide information about how the data was duplicated or whether the data has been duplicated automatically or has been copied manually by users.

**Comment by jason-fox** [comment]
You are correct, whether the data has been duplicated automatically or has been copied manually by users is not described within this tutorial since both options may be used dependent on need. It is possible to provision IoT devices to do this automatically within the documentation of the IoT Agent node library:

see https://iotagent-node-lib.readthedocs.io/en/latest/advanced-topics/index.html#ngsi-ld-linked-data-support

### NGSI-LD Linked Data support

`static_attributes` may be supplied with an additional `link` data element when provisioning an IoT Agent to ensure that
active attributes from the provisioned IoT Device may be maintained in parallel with a linked data entity . Take for
example a temperature gauge placed within a building. The **Device** data model literally represents the IoT device
itself, but the `temperature` attribute also needs to be shared with the **Building** entity

A `link` between them can be provisioned as shown:

e.g.:

```json
{
     "entity_type": "Device",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
..etc
     "attributes": [
        {"object_id": "l", "name": "temperature", "type":"Float",
          "metadata":{
              "unitCode":{"type": "Text", "value" :"CEL"}
          }
        }
     ],
     "static_attributes": [
        {
          "name": "controlledAsset",
          "type": "Relationship",
          "value": "urn:ngsi-ld:Building:001",
          "link": {
             "attributes": ["temperature"],
             "name": "providedBy",
             "type": "Building"
          }
        }
     ]
  }
```

Whenever a `temperature` measure is received **Device** is updated, and entity `urn:ngsi-ld:Building:001` is also
updated as shown:

```json
"temperature": {
    "type": "Property",
    "value": 27.6,
    "unitCode": "CEL",
    "providedBy": {
        "type": "Relationship",
        "object": "urn:ngsi-ld:Device:thermometer1"
    }
}
```

which is a _relationship-of-a-property_. An example in use can be seen here: https://github.com/FIWARE/tutorials.Time-Series-Data/blob/NGSI-LD/link-devices
